### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by ali-mnz** [VZiChoushaDui/Libertea#12]
Hi
I have installed it on Debian and got into the admin panel successfully
but when I create a new user and try to enter the link it provides, I get this error :

503 Service Unavailable
No server is available to handle this request.

**Comment by mkoushan** [comment]
same here.

**Comment by VZiChoushaDui** [comment]
Please try again with the latest version and see if this still occurs. If so, send me the logs from the install script.

**Comment by VZiChoushaDui** [comment]
I'm closing this issue as there has been no replies in the past 3 weeks.
