### ISSUE TITLE
line 256

### ISSUE THREAD

**Issue by Ros-ua** [VZiChoushaDui/Libertea#15]
./init.sh: line 256: dig: command not found

 Installation completed.
 Please visit panel to configure your VPN.

 Panel addresses:
   https://xxx/43c7bfea-2890-40c7-b9ad-7e405a5a0e77/
   https://xxx/43c7bfea-2890-40c7-b9ad-7e405a5a0e77/

 Username: admin
 Password: xxx
 
 and it is not working after i get this result

**Comment by VZiChoushaDui** [comment]
Please try again with the latest version and see if this still occurs. If so, send me the logs from the install script.

**Comment by VZiChoushaDui** [comment]
I'm closing this issue as there has been no replies in the past 3 weeks.
