### ISSUE TITLE
HTTP camouflage

### ISSUE THREAD

**Issue by Mobinoo1383** [VZiChoushaDui/Libertea#16]
It would be good if there was an option to choose a handful of camouflages in order for the panel to change the camouflage between these

**Comment by VZiChoushaDui** [comment]
Can you explain what value does having multiple camouflage domains add, and how you imagine it would work on Libertea?

**Comment by Mobinoo1383** [comment]
I actually misunderstood the meaning of http camouflage 
So I don't think using multiple http camouflage's would be beneficial
