### ISSUE TITLE
ip limit doesn't work

### ISSUE THREAD

**Issue by Mobinoo1383** [VZiChoushaDui/Libertea#19]
I tried it and it doesn't work

**Comment by VZiChoushaDui** [comment]
Can you explain how you're testing it, what is the expected behavior, and what is the observed result?

**Comment by Mobinoo1383** [comment]
I had clash on my android tv 
And stash on My iPhone 
I set the ip limit for user to 1
And then turned stash vpn on from my iPhone 
And then turned clash vpn on in my Android tv 
And they both worked 
But I expected the clash on my android tv to not work as I was currently running the vpn on my iPhone regarding the fact that the user configuration had 1 ip limit

**Comment by VZiChoushaDui** [comment]
Isn't your phone and tv connected to the same wifi? In that case both your devices will count as one ip.

If that's not the case, please note that both devices should *appear* connected in Stash/Clash. It's just that they're fighting over available slot, so in every few minutes requests from one device fails while the other one succeeds.

**Comment by Mobinoo1383** [comment]
Thanks for your reply @VZiChoushaDui 
Oh i didn't know that
I thought it counts each device as a separate ip 
It would really be better if it counted each device as an ip 
Isn't that how top tier vpn providers work?
Because this way people who are connected to the same Wi-Fi could put a lot more load than they should on the server

**Comment by Mobinoo1383** [comment]
Thanks for your reply @VZiChoushaDui 
Oh i didn't know that
I thought it counts each device as a separate ip 
It would really be better if it counted each device as an ip 
Isn't that how top tier vpn providers work?
Because this way people who are connected to the same Wi-Fi could put a lot more load than they should on the server
