### ISSUE TITLE
Advanced domain option

### ISSUE THREAD

**Issue by Mobinoo1383** [VZiChoushaDui/Libertea#20]
What is it?

**Comment by manwithoutpant** [comment]
beside your domain you can use other domain that are using cloudflare cdn.

**Comment by Mobinoo1383** [comment]
I mean this feature 
You can put ip addresses in 
![image](https://user-images.githubusercontent.com/124462330/218636358-599ff528-5615-45d8-89d1-9270760f48f6.png)

**Comment by manwithoutpant** [comment]
(domain=ip) vice versa

**Comment by Mobinoo1383** [comment]
Thanks @manwithoutpant

**Comment by VZiChoushaDui** [comment]
Is this question resolved?

P.S. @Mobinoo1383 Your domains are visible in the screenshots you posted. Consider redacting the domain and IP addresses for your privacy.

**Comment by VZiChoushaDui** [comment]
I'm closing this issue as there has been no replies in the past 2 weeks.
