### ISSUE TITLE
Domains

### ISSUE THREAD

**Issue by Mobinoo1383** [VZiChoushaDui/Libertea#21]
I mistakenly added an empty domain and now I can't delete it
![image](https://user-images.githubusercontent.com/124462330/218582714-ced34496-c862-4843-a389-884bbfd20165.png)
When I tap on it it doesn't redirect me to the domain options page

**Comment by manwithoutpant** [comment]
I do not have a solution for your problem, but try adding a domain name with a different TLD, in case of a ban, for example .pro, your user will have a chance to have access.

**Comment by Mobinoo1383** [comment]
@

**Comment by Mobinoo1383** [comment]
Thanks @manwithoutpant 
I uninstalled it and then reinstalled it 
Didn't find another way
Also I've got another domain and soon I'll be getting more 
The more the better

**Comment by VZiChoushaDui** [comment]
This is fixed in the latest version.
