### ISSUE TITLE
Feature request:bulk users

### ISSUE THREAD

**Issue by Mobinoo1383** [VZiChoushaDui/Libertea#22]
Thanks for the good projects 
It's configs work on every single isp in my country Iran 
Would be good if I could create many users at once

**Comment by VZiChoushaDui** [comment]
You can use `user.sh` script to automate user creation.

Here's an example for creating "User 1" to "User 10":

    sudo bash
    cd /root/libertea
    for i in $(seq 1 10); do ./user.sh add "User $i"; done

You can edit the start and end index in the `seq 1 10` part of the script.
