### ISSUE TITLE
Whatsapp calls not working even with Trojan protocol

### ISSUE THREAD

**Issue by Mobinoo1383** [VZiChoushaDui/Libertea#24]
Hi @VZiChoushaDui i currently have one domain for my panel 
Two domains for my connections and two secondary proxies 
And whenever I call someone on whatsapp it freezes and doesn't connect

**Comment by VZiChoushaDui** [comment]
This is now fixed in the latest version. Please update your Libertea.

Furthermore, you can also enable other protocols now. Libertea will automatically use Trojan for whatsapp (and other udp) connections.

**Comment by VZiChoushaDui** [comment]
I'm closing this issue as there has been no replies in the past 2 weeks.
