### ISSUE TITLE
ERROR: Timeout while waiting for panel to start

### ISSUE THREAD

**Issue by Ros-ua** [VZiChoushaDui/Libertea#33]
ERROR: Timeout while waiting for panel to start.
       Please open an issue on https://github.com/VZiChoushaDui/Libertea/issues/new
       and include the following information:
       - component name: libertea-panel
       - OS: "Ubuntu"
       - OS version: "20.04"
       - Docker version: Docker version 23.0.1, build a5ee5b1
       Also include the output of the following command:
           tail -n 100 /tmp/libertea-panel.log

**Comment by Ros-ua** [comment]
root@all:~# tail -n 100 /tmp/libertea-panel.log
 -- reconnecting mongo client on pid 54609
Traceback (most recent call last):
  File "/root/libertea/panel/./panel/__init__.py", line 20, in periodic_update_domains
    domains = utils.get_domains()
  File "/root/libertea/panel/./panel/utils.py", line 174, in get_domains
    all_domains = [domain["_id"] for domain in domains.find()]
  File "/root/libertea/panel/./panel/utils.py", line 174, in <listcomp>
    all_domains = [domain["_id"] for domain in domains.find()]
  File "/usr/local/lib/python3.8/dist-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.8/dist-packages/pymongo/cursor.py", line 1139, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/usr/local/lib/python3.8/dist-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib/python3.8/dist-packages/pymongo/mongo_client.py", line 1685, in __start_session
    self._topology._check_implicit_session_support()
  File "/usr/local/lib/python3.8/dist-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/usr/local/lib/python3.8/dist-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/usr/local/lib/python3.8/dist-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 5.0s, Topology Description: <TopologyDescription id: 641c578c796ab459405baba5, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>
Thu Mar 23 14:43:45 2023 - error managing signal 0 on worker 2
Updating max_ips cache
Updating max_ips cache
 -- reconnecting mongo client on pid 54610
[2023-03-23 14:43:54] Libertea panel serve script
[2023-03-23 14:43:54] Current directory: /root/libertea/panel
[2023-03-23 14:43:54] Checking net.core.somaxconn value
[2023-03-23 14:43:54]   net.core.somaxconn value is 32768
[2023-03-23 14:43:54] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
*** Starting uWSGI 2.0.21 (64bit) on [Thu Mar 23 14:43:54 2023] ***
compiled with version: 9.4.0 on 16 March 2023 15:18:08
os: Linux-5.4.0-144-generic #161-Ubuntu SMP Fri Feb 3 14:49:04 UTC 2023
nodename: all.zgc.su
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /root/libertea/panel
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 31468
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:1000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:20905 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x559842bb9030
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 512 connections
your mercy for graceful operations on workers is 60 seconds
mapped 510328 bytes (498 KB) for 6 cores
*** Operational MODE: preforking ***
Initializing...
[uwsgi-signal] signum 0 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 1 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 2 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 3 registered (wid: 0 modifier1: 0 target: default, any worker)
Updating HAProxy lists
 -- creating mongo client on pid 66873
Wrote 1 users to haproxy-lists/valid-user-endpoints.lst
Wrote 2 users to haproxy-lists/valid-panel-endpoints.lst
**** Reloading haproxy container ****
Wrote 1 domains to haproxy-lists/domains.lst
**** Reloading haproxy container ****
Wrote 1 domains to haproxy-lists/camouflage-hosts.lst
**** Reloading haproxy container ****
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x559842bb9030 pid: 66873 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 66873)
spawned uWSGI worker 1 (pid: 66966, cores: 1)
spawned uWSGI worker 2 (pid: 66967, cores: 1)
spawned uWSGI worker 3 (pid: 66968, cores: 1)
spawned uWSGI worker 4 (pid: 66969, cores: 1)
spawned uWSGI worker 5 (pid: 66970, cores: 1)
spawned uWSGI worker 6 (pid: 66971, cores: 1)
spawned uWSGI http 1 (pid: 66972)
libertea-haproxy
libertea-haproxy
Updating max_ips cache
 -- creating mongo client on pid 66969
Updating max_ips cache
 -- creating mongo client on pid 66966
Updating max_ips cache
 -- creating mongo client on pid 66967
Updating max_ips cache
 -- creating mongo client on pid 66970
Updating max_ips cache
 -- creating mongo client on pid 66968
root@all:~#

**Comment by Ros-ua** [comment]
-- reconnecting mongo client on pid 54609
Traceback (most recent call last):
  File "/root/libertea/panel/./panel/__init__.py", line 20, in periodic_update_domains
    domains = utils.get_domains()
  File "/root/libertea/panel/./panel/utils.py", line 174, in get_domains
    all_domains = [domain["_id"] for domain in domains.find()]
  File "/root/libertea/panel/./panel/utils.py", line 174, in <listcomp>
    all_domains = [domain["_id"] for domain in domains.find()]
  File "/usr/local/lib/python3.8/dist-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.8/dist-packages/pymongo/cursor.py", line 1139, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/usr/local/lib/python3.8/dist-packages/pymongo/mongo_client.py", line 1740, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib/python3.8/dist-packages/pymongo/mongo_client.py", line 1685, in __start_session
    self._topology._check_implicit_session_support()
  File "/usr/local/lib/python3.8/dist-packages/pymongo/topology.py", line 538, in _check_implicit_session_support
    self._check_session_support()
  File "/usr/local/lib/python3.8/dist-packages/pymongo/topology.py", line 554, in _check_session_support
    self._select_servers_loop(
  File "/usr/local/lib/python3.8/dist-packages/pymongo/topology.py", line 238, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 5.0s, Topology Description: <TopologyDescription id: 641c578c796ab459405baba5, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>
Thu Mar 23 14:43:45 2023 - error managing signal 0 on worker 2
Updating max_ips cache
Updating max_ips cache
 -- reconnecting mongo client on pid 54610
[2023-03-23 14:43:54] Libertea panel serve script
[2023-03-23 14:43:54] Current directory: /root/libertea/panel
[2023-03-23 14:43:54] Checking net.core.somaxconn value
[2023-03-23 14:43:54]   net.core.somaxconn value is 32768
[2023-03-23 14:43:54] Starting Libertea panel via uwsgi on port 1000 with 6 threads, and listen queue size of 512
*** Starting uWSGI 2.0.21 (64bit) on [Thu Mar 23 14:43:54 2023] ***
compiled with version: 9.4.0 on 16 March 2023 15:18:08
os: Linux-5.4.0-144-generic #161-Ubuntu SMP Fri Feb 3 14:49:04 UTC 2023
nodename: all.zgc.su
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /root/libertea/panel
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 31468
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:1000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:20905 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x559842bb9030
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 512 connections
your mercy for graceful operations on workers is 60 seconds
mapped 510328 bytes (498 KB) for 6 cores
*** Operational MODE: preforking ***
Initializing...
[uwsgi-signal] signum 0 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 1 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 2 registered (wid: 0 modifier1: 0 target: default, any worker)
[uwsgi-signal] signum 3 registered (wid: 0 modifier1: 0 target: default, any worker)
Updating HAProxy lists
 -- creating mongo client on pid 66873
Wrote 1 users to haproxy-lists/valid-user-endpoints.lst
Wrote 2 users to haproxy-lists/valid-panel-endpoints.lst
**** Reloading haproxy container ****
Wrote 1 domains to haproxy-lists/domains.lst
**** Reloading haproxy container ****
Wrote 1 domains to haproxy-lists/camouflage-hosts.lst
**** Reloading haproxy container ****
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x559842bb9030 pid: 66873 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 66873)
spawned uWSGI worker 1 (pid: 66966, cores: 1)
spawned uWSGI worker 2 (pid: 66967, cores: 1)
spawned uWSGI worker 3 (pid: 66968, cores: 1)
spawned uWSGI worker 4 (pid: 66969, cores: 1)
spawned uWSGI worker 5 (pid: 66970, cores: 1)
spawned uWSGI worker 6 (pid: 66971, cores: 1)
spawned uWSGI http 1 (pid: 66972)
libertea-haproxy
libertea-haproxy
Updating max_ips cache
 -- creating mongo client on pid 66969
Updating max_ips cache
 -- creating mongo client on pid 66966
Updating max_ips cache
 -- creating mongo client on pid 66967
Updating max_ips cache
 -- creating mongo client on pid 66970
Updating max_ips cache
 -- creating mongo client on pid 66968

**Comment by VZiChoushaDui** [comment]
@Ros-ua Can you give me the result for running the following two commands on a root shell on your server?

1. `curl -I http://localhost:1000`
2. `cd /root/libertea && set -o allexport && . .env && curl -I http://localhost:1000/$PANEL_ADMIN_UUID/`

**Comment by Ros-ua** [comment]
Hello, sir
i tried again a few more times to update
and on the second date, the update succeeded 
i will give you the results when getting them one more time
