### ISSUE TITLE
Request to have singed SSL on Libertea panel

### ISSUE THREAD

**Issue by LightMoon** [VZiChoushaDui/Libertea#34]
Hi Developers,

This is a feature request, please consider integrating the Libertea panel with the certbot or acme. 

Thanks.

**Comment by VZiChoushaDui** [comment]
At the moment Libertea relies on CDN to issue a valid certificate, but we will also add this soon.

**Comment by VZiChoushaDui** [comment]
Libertea v1031 now supports automatic certificate generation via LetsEncrypt. Please update to latest version.
