### ISSUE TITLE
Replacing the ssl certificate

### ISSUE THREAD

**Issue by maliohammad** [VZiChoushaDui/Libertea#36]
Hello, after installing liberta I am having trouble with the ssl certificate it got me (it says it is self signed). I would like to manually create one using acme script, but where should I place the new ssl certificate, and do I need to change something to prevent the script from overriding it?

**Comment by VZiChoushaDui** [comment]
Libertea v1031 supports automatic certificate generation via LetsEncrypt. Please update to latest version.

However, you can also install your own domain certificates by putting them in `/etc/ssl/ha-certs/` folder; then go to settings page and just click Save. Libertea will detect and use it.

**Comment by maliohammad** [comment]
I just checked it with filezilla and indeed it had a file name called "self signed .pem" so I just copy pasted the contents of a certificate I made myself with a CA into it and the problem seems to have been fixed. 
I am using a local CDN with proxy enabled, maybe that's why it failed.
