### ISSUE TITLE
not starting

### ISSUE THREAD

**Issue by Mohammad78SD** [VZiChoushaDui/Libertea#5]
hi
i tried to install this project on my vps twice
but every single time it doesnt starts
![image](https://user-images.githubusercontent.com/67378157/215265242-e7ecc7cf-d3a7-4dfd-983c-c1d172482346.png)
it stuck on starting situation and the panel not works for me
any idea how to fix it?

**Comment by Mohammad78SD** [comment]
I ran the update script again
now it started successfully but I cant access the panel again
I'm getting error 521 from cloudflare

**Comment by MrAlishr** [comment]
> I ran the update script again now it started successfully but I cant access the panel again I'm getting error 521 from cloudflare

I faced This Issue Too its cuz ha proxy and mongodb keeps restarting , i think its cuz :
`2023-01-28T15:21:36.810456736Z {"t":{"$date":"2023-01-28T15:21:36.809+00:00"},"s":"I",  "c":"NETWORK",  "id":4784918, "ctx":"initandlisten","msg":"Shutting down the ReplicaSetMonitor"}
`

**Comment by Mohammad78SD** [comment]
I rescaled my vps and it fixed the issue.

**Comment by VZiChoushaDui** [comment]
@Mohammad78SD Just shut down/remove the secondary proxy server. It will be automatically removed after a few minutes.

@MrAlishr Does your mongo still restarts? Please post the complete log for it.

**Comment by Mohammad78SD** [comment]
It's AWSOME.
Please keep the script update.
Thanks a lot.

**Comment by MrAlishr** [comment]
> @MrAlishr Does your mongo still restarts? Please post the complete log for it.

Well now I'm using phone but i trace back all erorrs an found the misconfiguration in the haproxy
Logs in docker logs : 
```
[WARNING]  (12) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:23]: 'log-format' overrides previous 'option httplog' in 'defaults' section.
[WARNING]  (12) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:83] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[WARNING]  (12) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:86] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[ALERT]    (12) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:88] : error detected while parsing ACL 'valid_panel' : failed to open pattern file </haproxy-files/lists/valid-panel-endpoints.lst>.
[ALERT]    (12) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:89] : error detected while parsing switching rule : no such ACL : 'valid_panel'.
[WARNING]  (12) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:93] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[WARNING]  (12) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:94] : a 'http-request' rule placed after a 'use_backend' rule will still be processed before.
[ALERT]    (12) : config : Error(s) found in configuration file : /usr/local/etc/haproxy/haproxy.cfg
[ALERT]    (12) : config : Fatal errors found in configuration.
```
