### ISSUE TITLE
Port 443 busy by another services

### ISSUE THREAD

**Issue by alidashti98** [VZiChoushaDui/Libertea#64]
On my Ubuntu 22 OS, port 443 is busy. Is there any way to install Libertea on another custom port?

**Comment by VZiChoushaDui** [comment]
It's not currently possible, but you can use Libertea's haproxy for your other traffic as well. to do so, just modify Libertea's haproxy configuration file and then restart docker.

**Comment by alidashti98** [comment]
Libertea install on docker? If use docker i can change port

**Comment by VZiChoushaDui** [comment]
You can modify the haproxy config to change port, but it's not guaranteed to work (Libertea assumes it's always accessible on port 443).

The better way is to keep Libertea's haproxy as the main entry point for all your server, and route your other traffic from there.

**Comment by Cyrus-of-Persia** [comment]
would you explain how to modify the haproxy config ?
