### ISSUE TITLE
Using the main domain on the main server for the fake website

### ISSUE THREAD

**Issue by NimaTarlani** [VZiChoushaDui/Libertea#71]
Can we create a local website in server, for example: localhost:5500
And set this for the fake website. It is behind both CDN and our main website

**Comment by VZiChoushaDui** [comment]
I think it should be possible with minor modifications. Will add it soon.

**Comment by VZiChoushaDui** [comment]
This is now possible in v1042. [see this](https://github.com/VZiChoushaDui/Libertea?tab=readme-ov-file#i-want-to-have-my-own-website-on-the-same-server-running-on-port-80443-can-i-still-use-libertea).
