### ISSUE TITLE
Error while installing pannel

### ISSUE THREAD

**Issue by csharpfarsi** [VZiChoushaDui/Libertea#72]
** Waiting for services to start...
    ✅ libertea-log-parser started
    ✅ libertea-provider-trojan-ws started
    ✅ libertea-provider-trojan-grpc started
    ✅ libertea-mongodb started
    ✅ libertea-provider-vless-grpc started
    ✅ libertea-rsyslog started
    ✅ libertea-provider-vmess-grpc started
    ✅ libertea-provider-vless-ws started
    ✅ libertea-provider-shadowsocks-v2ray started
    ✅ libertea-haproxy started
    ❌ libertea-panel failed to start. Retrying...

ERROR: Timeout while waiting for panel to start.
       Please open an issue on https://github.com/VZiChoushaDui/Libertea/issues/new
       and include the following information:

when i installing resiving this message how can i fix?

**Comment by urdudewithkali** [comment]
if you use ubuntu 20 just know that i doesn't work with it 
u should use ubuntu 22

**Comment by csharpfarsi** [comment]
i tried in both operation system's 

i got error on both(20,22)

i also checked it with another server location still getting error

**Comment by VZiChoushaDui** [comment]
The issue with Ubuntu 20 is fixed in the new version. Please install Libertea again.

If you're still having issues after reinstall, please run the following command and post the result:
 
    tail -n 100 /tmp/libertea-panel.log

**Comment by csharpfarsi** [comment]
thanks it worked for me now on ubounto 22.tnx a lot
