### ISSUE TITLE
Check ssh port for changes before setting firewall rules

### ISSUE THREAD

**Issue by hamid1626** [VZiChoushaDui/Libertea#73]
after adding tunnel Secondary Proxies with SSH connection I can't login the primary server with SSH (no putty no VPS console)
![Untitled](https://github.com/VZiChoushaDui/Libertea/assets/31160908/bd0c4a9c-959b-4396-8134-037e37679185)

do you have any suggestions?

**Comment by VZiChoushaDui** [comment]
what's the error when connecting to ssh?

**Comment by VZiChoushaDui** [comment]
Libertea shouldn't disable ssh port. idk what's going on there.

as for the vps console, try pressing ctrl+alt+f1 and then ctrl+alt+f2 and then ctrl+alt+f3 (up to f6). this switches the active virtual console. you might have login prompt on tty2 (accessible via ctrl+alt+f2, for example).

**Comment by hamid1626** [comment]
thanks for supporting, I login with tty2...but I can't login with Putty and bitvise ,maybe it depends on this image?
![Untitled](https://github.com/VZiChoushaDui/Libertea/assets/31160908/59d87b47-11bc-4fb9-8b9f-99551c92f15f)

**Comment by hamid1626** [comment]
The problem was the firewall activated maybe after the installation, so there was  SSH port that changed not added 
However, thanks for responding and supporting

**Comment by VZiChoushaDui** [comment]
Ah. Libertea activates the firewall but does not check for ssh port changes. Reopening so we can track this.

**Comment by VZiChoushaDui** [comment]
Fixed.
