### ISSUE TITLE
مدیریت کاربران

### ISSUE THREAD

**Issue by shinse110** [VZiChoushaDui/Libertea#77]
چرا مدیریت کاربران انقدر ناقصه؟
چندتا چیز کم داره
1. تاریخ ایجاد هر کاربر مشخص نیست
2.نمیشه زمان هر کاربر رو مدیریت کرد و هر کاربر بصورت پیش فرض نامحدود زمانی هست
3. مدیریت حجم هم لازمه که برای هر کاربر بصورت انتخابی نامحدود یا حجمی تعریف بشه
پیروز و مانا باشید

بشدت منتظر آپدیت جدید شما هستیم

-----

(translated by google)
Why is user management so incomplete?
It lacks a few things

The date of creation of each user is not known
2. It is not possible to manage the time of each user and each user has unlimited time by default
Traffic management is also required to be defined for each user as unlimited
Be victorious and mana
We are waiting for your new update

**Comment by VZiChoushaDui** [comment]
We're working on adding time and traffic limitations soon.

**Comment by VZiChoushaDui** [comment]
This is now available on version 1043.
