### ISSUE TITLE
SNI in Secondary config

### ISSUE THREAD

**Issue by Mahdadii** [VZiChoushaDui/Libertea#79]
In the configuration provided for the tunnel server, the fake address we gave is registered and we have to change SNI to our domain to make it work.
Thank you for fixing it in the next update or giving a solution so that we don't have to change them manually.
Thankful

**Comment by VZiChoushaDui** [comment]
If you're talking about v2ray clients, you don't need to add sni, you just have to manually tick "allow insecure" for it to work.

But we're adding domain support as well soon.

**Comment by VZiChoushaDui** [comment]
Domain support is also added.
