### ISSUE TITLE
Bug in Secondary Proxies section

### ISSUE THREAD

**Issue by hdaryanavard** [VZiChoushaDui/Libertea#82]
When we remove the proxy from the Routes menu due to its deactivation and add the same proxy again, even though this proxy is activated, it is not displayed in the Routes menu and in the Secondary Proxies. In other words, when we remove the proxy from the menu, if we add the same proxy again, it will not be displayed in the menu, even though it is activated and available.

**Comment by VZiChoushaDui** [comment]
Fixed
