### ISSUE TITLE
How to use Libertea by Nginx 

### ISSUE THREAD

**Issue by hesamz3090** [VZiChoushaDui/Libertea#85]
I have two sites running on Nginx, each on a different subdomain. However, when installing Libertea, Nginx prevents it from running, showing the following error:

```
ERROR: Your panel domain [example.domain.com](http://example.domain.com/) is not accessible.
       Please ensure that your domain's DNS is pointing to the server's IP (***.***.***.***).
```

Turning off Nginx resolves the issue, but I'm unable to do so. What should I do in this situation ?

**Comment by VZiChoushaDui** [comment]
Run your nginx on another port (like 8080), and set Libertea's camouflage domain to `127.0.0.1:8080`.

[More info](https://github.com/VZiChoushaDui/Libertea?tab=readme-ov-file#i-want-to-have-my-own-website-on-the-same-server-running-on-port-80443-can-i-still-use-libertea)
